# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


appearance:
  theme_day: escher_bw
  theme_night: minimal
  font: native
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Scientist at the Institute for Physical Science and Technology; Black holes, hyperboloidal foliations, null infinity'
    twitter: 'AnilZenginoglu'
  analytics:
    google_analytics: 'G-1Q5LP68RP1'
    baidu_tongji: ''
  verification:
    google: 'CVDtdnmvDztdvP8XA_Fh0StEBOfqy3DM5L6GyojfVgk'
    baidu: ''


# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: dracula
    # theme_dark: 
    enable: true
    extra_languages:
      - python
      - html
      - latex
    # theme: "dracula"
    # highlight_style: "solarized-dark"

  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/anilzen/anilzen.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  # cms:
  #   branch: main
  #   local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
  
# icon:
#   pack:
#     ai: true