name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false 
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.126.3'
          extended: true

      - name: Build
        # run: env HUGO_ENV="production" WC_POST_CSS="true" hugo --gc --minify -b https://anilzen.github.io
        run: hugo --gc --minify -b https://anilzen.github.io

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
